spring:
  application:
    name: Spring-Exercices
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: password
server:
  port: 8081